# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a8423dae5f9cc32b8f2d465d994d4205175691ebb090c13d094423eeebde9374074f122cd932eeb45b6fd6d6dcd376a2914852699d9b13528ea19a8bcba19eab

test:
  secret_key_base: 556bf02cd71c177ff41cda524d7fdee0f6c8f1691e51c950d96da69d49f6c76036ee75520ac22b31e34068e74331fa2ef9ea1286ffdbb9f68a3a72d6565aa272

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
